# hebi_motor:                    
    # Publish joint states ----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

    # Position controllers --------------------------------
hebi_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - Arm/J1_shoulder
      - shoulder_elbow/OUTPUT_JOINT
    pid: { p: 50, d: 0.0, i: 0.0 }


#     gains:
#         Arm/J1_shoulder: { p: 50, d: 0.0, i: 0.0 }
#         shoulder_elbow/OUTPUT_JOINT: { p: 50, d: 0.0, i: 0.0 }
