// Generated by gencpp from file hebi_motor/custom_msg.msg
// DO NOT EDIT!


#ifndef HEBI_MOTOR_MESSAGE_CUSTOM_MSG_H
#define HEBI_MOTOR_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebi_motor
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : num_float(0.0)  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : num_float(0.0)  {
  (void)_alloc;
    }



   typedef double _num_float_type;
  _num_float_type num_float;





  typedef boost::shared_ptr< ::hebi_motor::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebi_motor::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::hebi_motor::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::hebi_motor::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::hebi_motor::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebi_motor::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebi_motor::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hebi_motor::custom_msg_<ContainerAllocator1> & lhs, const ::hebi_motor::custom_msg_<ContainerAllocator2> & rhs)
{
  return lhs.num_float == rhs.num_float;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hebi_motor::custom_msg_<ContainerAllocator1> & lhs, const ::hebi_motor::custom_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hebi_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hebi_motor::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebi_motor::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_motor::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_motor::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_motor::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_motor::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebi_motor::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b62cff7d3666b686e1901448794166aa";
  }

  static const char* value(const ::hebi_motor::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb62cff7d3666b686ULL;
  static const uint64_t static_value2 = 0xe1901448794166aaULL;
};

template<class ContainerAllocator>
struct DataType< ::hebi_motor::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebi_motor/custom_msg";
  }

  static const char* value(const ::hebi_motor::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebi_motor::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 num_float\n"
;
  }

  static const char* value(const ::hebi_motor::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebi_motor::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_float);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebi_motor::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebi_motor::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "num_float: ";
    Printer<double>::stream(s, indent + "  ", v.num_float);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBI_MOTOR_MESSAGE_CUSTOM_MSG_H
