controller_list:
  - name: hebi_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Arm/J1_shoulder
      - shoulder_elbow/OUTPUT_JOINT
